[eeprom_tlv_info] Optimize EEPROM data process by using visitor pattern
Junchao-Mellanox/sonic-platform-common pull request #12
Opened 2021-05-21 05:41 UTC by Junchao-Mellanox

#### Description

1. Use visitor pattern accessing EEPROM data
2. Provide utility functions to access redis data base

#### Motivation and Context

Remove EEPROM cache file and use DB instead

#### How Has This Been Tested?

Manual test and regression test

#### Additional Information (Optional)

2021-06-01 16:31 UTC, jleveque requested changes

2021-06-01 16:31 UTC, jleveque commented on sonic_platform_base/sonic_eeprom/eeprom_tlvinfo.py
> +           but the inpurt arguments will all be None.
s/inpurt/input/

2021-06-03 15:52 UTC, jleveque requested changes

2021-06-03 15:52 UTC, jleveque commented on sonic_platform_base/sonic_eeprom/eeprom_base.py
> +        # Redis STATE_DB, cached data should be feched from STATE_DB.EEPROM_INFO.
s/feched/fetched/

2021-06-03 15:52 UTC, jleveque commented on sonic_platform_base/sonic_eeprom/eeprom_base.py
> +        # Redis STATE_DB, cached data should be feched from STATE_DB.EEPROM_INFO.
s/feched/fetched/

2021-06-03 15:52 UTC, jleveque commented on sonic_platform_base/sonic_eeprom/eeprom_base.py
> +        # Redis STATE_DB, cached data should be feched from STATE_DB.EEPROM_INFO. This
s/feched/fetched/

2021-06-03 15:52 UTC, jleveque commented on sonic_platform_base/sonic_eeprom/eeprom_base.py
> +                # Redis STATE_DB, cached data should be feched from STATE_DB.EEPROM_INFO. This
s/feched/fetched/

2021-06-03 15:52 UTC, jleveque commented on sonic_platform_base/sonic_eeprom/eeprom_base.py
> +        # Redis STATE_DB, cached data should be feched from STATE_DB.EEPROM_INFO.
s/feched/fetched/

2021-06-03 15:52 UTC, jleveque commented on sonic_platform_base/sonic_eeprom/eeprom_base.py
> +        # Redis STATE_DB, cached data should be feched from STATE_DB.EEPROM_INFO.
s/feched/fetched/

2021-06-03 15:52 UTC, jleveque commented on sonic_platform_base/sonic_eeprom/eeprom_base.py
> +                # code need to be adjusted once cache file is completely removing from the system.
s/need/needs/
s/removing/removed/

2021-06-07 01:53 UTC, keboliu approved these changes

2021-06-07 05:56 UTC, closed without merging